### ISSUE TITLE
"Work with my organizations" dropdown is not populating

### ISSUE THREAD

**Issue by pitviper6** [NLightenGroup/nlighten-ontology#10]
I've created and published an organization, but there is nothing in the dropdown menu in 'Work with my organizations'

**Comment by nicolevasilevsky** [comment]
+1

**Comment by skcheng** [comment]
There was a problem with the initial repository installation. This is now all set, organizations are showing up in the drop down.

**Comment by nicolevasilevsky** [comment]
I can see the org that @pitviper6 created, but when I create a new org, it isn't showing up

**Comment by nicolevasilevsky** [comment]
the dropbox is also not working on the [organization page](https://alaska.dev.eagle-i.net/sweet/#history?stubView=false&initResourcesView=false&referencesView=false&mode=view&typeUri=http://vivoweb.org/ontology/core%23GovernmentAgency&typeLabel=Government%20Agency&instanceUri=http://alaska.dev.eagle-i.net/i/00000160-37f4-4c89-4489-507d80000000&instanceLabel=testing&providerUri=http://alaska.dev.eagle-i.net/i/00000160-37f4-4c89-4489-507d80000000&providerLabel=testing), on the side bar:

Click on the select an organization dropbox, all the orgs should show up, but only the org that Juliane created does.

![image](https://user-images.githubusercontent.com/6722114/33790569-1aa4e8b6-dc36-11e7-9df4-bd5032205d4f.png)

**Comment by nicolevasilevsky** [comment]
This seems to be working now (in both places) for new organizations I've created.

**Comment by nicolevasilevsky** [comment]
I think the issue is if a more specific organization is not selected, it doesn't show up. If you just leave it as 'organization', it won't show up in the dropdown.

**Comment by skcheng** [comment]
@nicolevasilevsky I think this is by design. I know I've run into this a few times trying to test out something on eagle-i and gotten stuck because I created an Organization, and not a more specific one.
