### ISSUE TITLE
should there only be three types of organizations?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#13]
![image](https://user-images.githubusercontent.com/6722114/33783749-dc99e3dc-dc12-11e7-9db7-4e7ec254b243.png)
Is it intentional to only have three orgs in the ontology?

**Comment by marijane** [comment]
For NLighten 1.0, the only organizations providing resources are OSU, Harvard, and the FDA.  

There were early inquiries about whether OHSU has any resources to provide but I have no idea who to ask about that.
