### ISSUE TITLE
there are a lot of extra fields showing up for organization

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#15]
most of the fields on the organization record are irrelevant

**Comment by nicolevasilevsky** [comment]
this seems to be the case for all the records

**Comment by skcheng** [comment]
I think the annotation:
`http://eagle-i.org/ont/app/1.0/PropertyGroup_DataModelExclude`
needs to be added to the properties shouldn't be shown in the nln-app.owl

**Comment by nicolevasilevsky** [comment]
We did all that in the app file. Not sure why the properties are still showing up?

![image](https://user-images.githubusercontent.com/6722114/33785299-3838278e-dc19-11e7-9353-94e369e65d5f.png)

**Comment by nicolevasilevsky** [comment]
Oh wait, looks like the wrong URL!

**Comment by nicolevasilevsky** [comment]
I will fix it now in the ontology

**Comment by nicolevasilevsky** [comment]
ok, committed. do you need to reload the ontology, @skcheng?

**Comment by skcheng** [comment]
@nicolevasilevsky yes, I'll need to rebuild & reload the ontology. I'm going to try a hot swap.

**Comment by nicolevasilevsky** [comment]
unfortunately, these extra fields are still showing up

**Comment by skcheng** [comment]
@nicolevasilevsky dang it. Which fields shouldn't be showing up based on how they've been annotated? Can you take a look again? I'm no longer seeing `has 2d boundary` in SWEET.

I looked at the definition on the ontology browser for Organization and SWEET is currently showing a subset of the properties that are listed in the ontology browser.

**Comment by skcheng** [comment]
Actually, correction. There was an `ClassGroup_InstanceCreate` annotation in the app layer for `http://xmlns.com/foaf/0.1/Agent`. I removed this and I think it now looks more like what you might be expecting:
<img width="1087" alt="screen shot 2017-12-09 at 4 41 30 pm" src="https://user-images.githubusercontent.com/1533193/33799760-133fc490-dd00-11e7-89a6-87260c1a2014.png">

I've deployed this to: https://jsu.dev.eagle-i.net/sweet
