### ISSUE TITLE
do we want the term request pop up to link to the ERO tracker?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#16]
![image](https://user-images.githubusercontent.com/6722114/33783929-a36a8520-dc13-11e7-9716-59959bc0a2f9.png)
Should add a link to this tracker instead, yes?

**Comment by marijane** [comment]
hmmm no it should not be the ERO tracker and yes this tracker should be a fine place to redirect them instead.

**Comment by skcheng** [comment]
Changed wording in application and set the link to this tracker in the properties file.

**Comment by skcheng** [comment]
Deployed
