### ISSUE TITLE
should there be more than one type of educational resource?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#17]
![image](https://user-images.githubusercontent.com/6722114/33783959-be5fb990-dc13-11e7-8e81-498a4267d464.png)

seems like the ontology could be extended here?

**Comment by marijane** [comment]
For the moment these are all I know will be in the system for v1.0, and even the videos may end up wrapped in Common Cartridge packages.

 Suggestions welcome!

**Comment by nicolevasilevsky** [comment]
the first thing that came to my mind was open educational resources, but maybe we should think about other types that may be relevant

**Comment by marijane** [comment]
Everything in NLighten is going to be stuff from firewalled Learning Management Systems like Moodle, I am not sure there will be any OERs to catalog.

**Comment by nicolevasilevsky** [comment]
I see!
