### ISSUE TITLE
should add 'tool tips' 

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#18]
I am pretty sure the tool tips are derived from the data properties in the ontology.

See this example from eagle-i:
![image](https://user-images.githubusercontent.com/6722114/33784796-037bb1ac-dc17-11e7-93c3-12d19d2bb61a.png)

and this is in ERO:
![image](https://user-images.githubusercontent.com/6722114/33784812-154892ec-dc17-11e7-8a63-18d8c436ac77.png)

**Comment by marijane** [comment]
do we know which property it comes from? 

that list of data properties has a ton of stuff that aren't part of my model...

**Comment by nicolevasilevsky** [comment]
I don't know, but I'll see if I can find any info about it in the documentation on open.med.

**Comment by nicolevasilevsky** [comment]
Does this help explain it?
https://open.med.harvard.edu/wiki/display/eaglei/Core+Task+Workflows+and+Scenarios

**Comment by marijane** [comment]
Yes!  thank you.

I only added Preferred Labels to entities that didn't already have the correct capitalization.  Do we need to add them to everything?  When I looked at ero-app.owl I thought I saw a lot of things that did not have preferred labels.

I did not add preferred definitions to anything, either.

**Comment by nicolevasilevsky** [comment]
From what I remember, we only added preferred labels if they didn't have the correct capitalization or if we wanted the display label to say something else - so just as you did. It is my understanding the software would use the preferred label, and if there wasn't one, it would use the proper label.

**Comment by marijane** [comment]
I just want to note that the software doesn't appear to be showing any tooltips, regardless of the annotation used.

**Comment by skcheng** [comment]
@marijane The annotation to use for the tooltips is: `app:preferredDefinition`

If the annotation doesn't exist, then the application will use whatever the definition is for the thing. You can see the definitions in the ontology browser by clicking on the properties: https://alaska.dev.eagle-i.net/model/#t=http://schema.org/CreativeWork&of=score

![untitled](https://user-images.githubusercontent.com/1533193/34003897-88a4588c-e0c4-11e7-9d09-3eda1452332a.png)

**Comment by marijane** [comment]
Interesting, everything shows up with NO DEFINITION despite lots of properties having an obo:definition annotation.  I will add some preferred definitions to see if that fixes this.

**Comment by marijane** [comment]
we now have tool tips!

**Comment by nicolevasilevsky** [comment]
woohoo!

Now some comments about the defs:
For contributor, the tool tip says secondary contributor for the resource. But it wouldn't necessarily be a secondary contributor would it? Maybe revise to a person or organization who contributed to the development of the resource.

Oh, I think i understand now - the primary person/org is the creator? If that is the case, then it would be nice to order that before contributor.

**Comment by marijane** [comment]
I agree, creator should come before contributor, and I pushed a change late Friday that does this, but I haven't made it part of a release yet.
