### ISSUE TITLE
autocomplete is not working for ontology terms

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#19]
Trying to add a new resource and autocomplete is not working for the educational resource type

![image](https://user-images.githubusercontent.com/6722114/33785886-de2e53fa-dc1b-11e7-84c7-a99e66172da7.png)

**Comment by skcheng** [comment]
Needed to update the properties file to look at alaska.dev for the autosuggest. File has been updated and this will be fixed on the next restart.
