### ISSUE TITLE
should 'person' be an option when creating an organization?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#20]
![image](https://user-images.githubusercontent.com/6722114/33786432-03e36ac0-dc1e-11e7-9d78-2e2bb2dd9898.png)

**Comment by marijane** [comment]
no.  this must have to do with their parent class being agent.

**Comment by nicolevasilevsky** [comment]
if the software specifies organization as the class for this field, then that should fix it, right? (not sure exactly how that works)

**Comment by marijane** [comment]
I don't know but I bet @skcheng knows!

**Comment by skcheng** [comment]
@marijane I think it might be the instanceCreate & primaryResourceType annotations associated with Person in the app layer file.

If I have this right, primary resource type is like saying the 'top level' resource. A person isn't exactly a resource, the way an organization isn't a resource.

**Comment by marijane** [comment]
I think I fixed this in b0d266661d70666a3a2b1ba04a32187d473307c2.  The app layer file still had some references to schema:Person with the instanceCreate and primaryResourceType annotations.
