### ISSUE TITLE
URLs don't work unless there is HTTPS in front

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#21]
The link out from a www url does not work. Is this expected behavior? Seems somewhat familiar.

![image](https://user-images.githubusercontent.com/6722114/33786513-4fc1d10c-dc1e-11e7-9845-3ae83dba671f.png)
![image](https://user-images.githubusercontent.com/6722114/33786522-55c51f00-dc1e-11e7-9466-112a9f9521a4.png)

**Comment by skcheng** [comment]
@nicolevasilevsky You have to write out the full url, including the `http://` or `https://`. If the protocol isn't in the link, the application will assume that it is a link relative to the application.
