### ISSUE TITLE
question about 'has member'

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#22]
In eagle-i, the 'has member' links to other person records in the repo. See screenshot of an example:
![image](https://user-images.githubusercontent.com/6722114/33786675-cea47704-dc1e-11e7-9498-fbc028e44f2c.png)

Should this be the case here too? Currently has member is free text:
![image](https://user-images.githubusercontent.com/6722114/33786657-c12f13fe-dc1e-11e7-9c66-a9b898469d5d.png)

**Comment by marijane** [comment]
i'm not sure what's going on here, "has member" is not a part of my model...?

**Comment by nicolevasilevsky** [comment]
it is a subclass of 'has part' object property

**Comment by marijane** [comment]
didn't we exclude 'has part'?

**Comment by nicolevasilevsky** [comment]
Yes! But it looks like all the excluded properties are still showing up for some reason. Do we have to have those in the ontology? What if we just deleted them if they are not needed?

**Comment by skcheng** [comment]
I think this has also been resolved with #15
