### ISSUE TITLE
'locked by me' link is not working

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#25]
when I go to [browse people and resources](https://alaska.dev.eagle-i.net/sweet/#history?stubView=false&initResourcesView=true&referencesView=false&mode=list&offset=0&limit=20&sortBy=name)
and click 'locked by me'
![image](https://user-images.githubusercontent.com/6722114/33790846-d3f73d58-dc38-11e7-867f-d88adef1a18d.png)
nothing shows up, even though I have records locked

**Comment by skcheng** [comment]
@nicolevasilevsky Try this:

1. From the workbench, click on `Browse people and resources`
2. From the left nav, click on `All Resource Types`
3. Now try to filter for locked by me/created by me.

**Comment by nicolevasilevsky** [comment]
currently I can't click on All Resource Types, I get this error

![image](https://user-images.githubusercontent.com/6722114/34057878-c4d1a50c-e18d-11e7-9f65-4f7f84981731.png)

**Comment by marijane** [comment]
I think this message is from when Sophia was deploying new ontology files.

**Comment by nicolevasilevsky** [comment]
yes, it was!
