### ISSUE TITLE
batch locking works for the record, but the red "locked" logo doesn't show up in the Org listing

### ISSUE THREAD

**Issue by pitviper6** [NLightenGroup/nlighten-ontology#27]
***The rest of the functions under the Action dropdown work as they should
1. I go into 'browse people and resources in my organization'
2. I choose 'Organization'
3. I click on the two organizations I've created, the Government of Juliane and University of Juliane, which are currently unlocked.
4. I choose 'Lock' on the 'Actions' dropdown
5. I get the popup asking me if I want to lock these records and I choose OK.
6. The records do become locked (see second image, it shows the record is indeed locked), but the red 'locked' image doesn't show up. (see first image)
7. I've tried refreshing, going back to the start and viewing the list again and the Organization listing never shows them as locked.

![lockedissue](https://user-images.githubusercontent.com/15837566/33800000-844516ae-dd05-11e7-9163-fc8aedc88a68.jpeg)
![lockedissue2](https://user-images.githubusercontent.com/15837566/33800001-8453080e-dd05-11e7-8e80-2667b9dc43d2.jpeg)

**Comment by skcheng** [comment]
@pitviper6 That's expected, the instance pages show the green padlock and in the list it shows up as a red padlock.

**Comment by marijane** [comment]
It sounds like this can be closed.  Someone can reopen it if I'm wrong.
