### ISSUE TITLE
Embedded classes - do Educational Resources have them?

### ISSUE THREAD

**Issue by pitviper6** [NLightenGroup/nlighten-ontology#29]
Just making sure that these records won't have embedded classes - I don't see any, but I want to make sure!

-Check embedded classes to ensure they are displaying correctly (for antibodies, constructs, interventional study)

**Comment by nicolevasilevsky** [comment]
Yes - the educational resources don't have any embedded classes.

**Comment by pitviper6** [comment]
WOO!
