### ISSUE TITLE
Can't open the Ontology Browser

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#30]
I get a 404:
![screen shot 2017-12-11 at 9 32 24 am](https://user-images.githubusercontent.com/1771847/33844786-3eec34b4-de56-11e7-8c28-90a657e5bc3c.png)

**Comment by skcheng** [comment]
@marijane That's expected, the links on the applications haven't been updated to be specific to N-Lighten.

**Comment by marijane** [comment]
got it, thanks.
