### ISSUE TITLE
Use app:domainConstraint & app:rangeConstraint for property

### ISSUE THREAD

**Issue by skcheng** [NLightenGroup/nlighten-ontology#32]
In the nln-app.owl file, please replace:

    
    <rdf:Description rdf:about="http://schema.org/provider">
        <rdfs:domain rdf:resource="http://schema.org/CreativeWork"/>
        <rdfs:range>
            <owl:Class>
                <owl:unionOf rdf:parseType="Collection">
                    <rdf:Description rdf:about="http://xmlns.com/foaf/0.1/Organization"/>
                    <rdf:Description rdf:about="http://xmlns.com/foaf/0.1/Person"/>
                </owl:unionOf>
            </owl:Class>
        </rdfs:range>
        <app:inPropertyGroup rdf:resource="http://eagle-i.org/ont/app/1.0/PropertyGroup_ResourceProvider"/>
        <rdfs:comment rdf:resource="http://eagle-i.org/ont/app/1.0/PropertyGroup_PrimaryProperty"/>
    </rdf:Description>

With:
```
    <!-- http://schema.org/provider -->
    <rdf:Description rdf:about="http://schema.org/provider">
        <app:domainConstraint rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://schema.org/CreativeWork</app:domainConstraint>
        <app:rangeConstraint rdf:datatype="http://www.w3.org/2001/XMLSchema#string">http://xmlns.com/foaf/0.1/Organization</app:rangeConstraint>
        <app:inPropertyGroup rdf:resource="http://eagle-i.org/ont/app/1.0/PropertyGroup_ResourceProvider"/>
        <rdfs:comment rdf:resource="http://eagle-i.org/ont/app/1.0/PropertyGroup_PrimaryProperty"/>
    </rdf:Description>
```

**Comment by marijane** [comment]
I added the constraint annotations in 224303f169372a40e6051430905f09e8e6954d2d.  I did not remove the domain/range assertions; I eventually want to move them back to nln.owl.
