### ISSUE TITLE
Does eagle-i automatically capitalize preferred labels on created resources?

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#36]
All the properties are capitalized in this view, but none of the labels or preferred labels for these resources are capitalized in the ontology or the application layer.

![screen shot 2017-12-12 at 1 42 28 pm](https://user-images.githubusercontent.com/1771847/33910061-5c6a434a-df42-11e7-997c-af650459b41d.png)

**Comment by nicolevasilevsky** [comment]
I don't think the software automatically capitalizes the labels, I think that is why we had the app file in the past, so we could add the capitals. Not sure why it is doing it here.

**Comment by skcheng** [comment]
I confirmed in the code... the application does capitalize the first letter in the `view` mode in SWEET (`InstanceWidgetUtils.createLabel`). I'm not sure why this isn't the case for the `edit` mode. It could be a bug and we've always just happened to have added annotations for `app:preferredLabel` that was capitalized.

**Comment by nicolevasilevsky** [comment]
interesting!

**Comment by marijane** [comment]
Nice to have confirmation that the software is doing this.  Thanks, @skcheng!
