### ISSUE TITLE
should you add preferred labels to data properties?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#42]
should you add preferred labels to data properties so they are capitalized?

when i go to create a new organization, the labels are lowercase:
![image](https://user-images.githubusercontent.com/6722114/33965868-5232d25e-e012-11e7-8b70-9595d7a19eab.png)

**Comment by marijane** [comment]
They actually do have preferred labels, for whatever reason I decided to make them all lowercase.

Should they be Sentence case or Title Case instead?

**Comment by nicolevasilevsky** [comment]
it's up to you! I think I'd go with Title Case.

**Comment by marijane** [comment]
Closed by 225721d1924e2ec9b632fc6224075d22a2401e9e
A few properties were relabeled in other commits, but this was the big one.

**Comment by marijane** [comment]
Oops, missed some.

**Comment by marijane** [comment]
Think I got them all in v2171215.1.
