### ISSUE TITLE
if you create a person record from an organization, should they automatically be a member of that org?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#43]
I created a new organization, and within that organization, I created a new person record.

![image](https://user-images.githubusercontent.com/6722114/33966006-c82f6184-e012-11e7-88d1-af4d7afa42d5.png)

This creates a resource stub.
![image](https://user-images.githubusercontent.com/6722114/33966010-d42c0abe-e012-11e7-9546-59ca2cadee5b.png)

If I click on that person, they are not automatically associated with that organization. I'm not sure if it behaved this way in eagle-i, maybe it did (seems like it should to me.)

![image](https://user-images.githubusercontent.com/6722114/33966039-ecdc64c8-e012-11e7-8342-f7ba6c26169c.png)

**Comment by marijane** [comment]
Do you mean it should automatically populate member_of on the Person instance?

**Comment by nicolevasilevsky** [comment]
yes

**Comment by marijane** [comment]
I agree it should do that!  I wonder how we might make that happen.

**Comment by nicolevasilevsky** [comment]
@skcheng is there a sandbox for eagle-i where I could test if this is set up this way in the eagle-i sweet?

**Comment by skcheng** [comment]
@nicolevasilevsky if by sandbox you mean some place you can created test resources and such to see, yes, I suggest using the qa tier. How about upr.qa? It looks like your account is still enabled.

**Comment by skcheng** [comment]
I think you need to annotate `member of` with `owl:inverseOf`

**Comment by nicolevasilevsky** [comment]
Thanks Sophia! It looks like in eagle-i, the person pages are not associated with organizations actually. Here is a screenshot of all the fields in eagle-i for a person record, not that we necessarily have to do things the same as eagle-i.

![image](https://user-images.githubusercontent.com/6722114/34011575-56c0cd22-e0c5-11e7-9875-5d143d18a155.png)

**Comment by marijane** [comment]
I'll add that member of and has member are both annotated with owl:inverseOf.

It is good to see all these metadata fields for people in eagle-i.  I may have been a bit too focused on the educational resources in my modeling efforts here.  I can pull in some more stuff from FOAF.

**Comment by marijane** [comment]
It sounds like there's nothing to do for this ticket since eagle-i doesn't do this automatically, but before we close it I want to confirm that people can be related to their organizations manually after completing their stub.  the ontology is set up for this, one of us just needs to confirm that it works.

**Comment by nicolevasilevsky** [comment]
yep, you can associate a person with an organization after creating the organization.

it works!

**Comment by marijane** [comment]
Yay!  closing this ticket.
