### ISSUE TITLE
Is Audience really a Resource Type?

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#45]
I found my way into the Ontology Browser and I notice that Audience is showing up in the Resource Type section.  I did not realize this is where it would show up, and I'm not sure it should, as it's not really a resource.  

* Maybe it's an Embedded Type?
* Maybe we should implement this as a Referenced Taxonomy?  This would mean defining a list of audiences in the ontology in advance, and making users request new terms if the audience they need to specify isn't there.  The current model lets people create Audience instances as they please, which can make a mess of things if people aren't careful.
* Should it also be a search facet?

![screen shot 2017-12-13 at 3 14 29 pm](https://user-images.githubusercontent.com/1771847/33967439-5fe74910-e018-11e7-8882-7aecb6fa2cba.png)

**Comment by nicolevasilevsky** [comment]
I think a reference taxonomy is a good idea, otherwise you are not going to get consistent entries.

**Comment by marijane** [comment]
Do you think the fact that you can pick from audiences created by all users can help avoid that?

I wish I had a better idea of what the audiences for NLighten content might be.

**Comment by nicolevasilevsky** [comment]
Oh yeah, I didn't realize that. I think it is good as is then. :)

**Comment by marijane** [comment]
Per Sophia's email today about fixing the institution search, it sounds like I should try putting this in the SearchFlatten group.
