### ISSUE TITLE
two properties for audience

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#46]
there is a free text field for audience (which is maybe coming from the resource type? see #45) and there is the embedded class, has audience

![image](https://user-images.githubusercontent.com/6722114/33967893-45517344-e01a-11e7-8c06-e8b9248a7bd1.png)

**Comment by marijane** [comment]
Per #48, the domain on audienceType is wrong, and even when corrected it might be redundant.
