### ISSUE TITLE
Should we reconsider the use of schema:Duration?

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#47]
nln.owl pulls in [schema:Duration](http://schema.org/Duration) as it's defined in the schema.org vocabulary, but upon closer inspection, it seems that all of the properties that have a Duration as an object are implemented in practice as string literals in ISO 8601 format.  (This makes some amount of sense when you remember that schema.org is an RDF vocabulary rather than an OWL vocabulary, and that its properties are defined as rdf:Property rather than owl:ObjectProperty or owl:DatatypeProperty.)

If I were to change this, I would:

- [x] Remove the schema:Duration class

- [x] Redefine schema:duration and schema:timeRequired as Datatype Properties with the range of xsd:dateTime.

**Comment by marijane** [comment]
Issues highlighted in other tickets support the argument in favor of refactoring this.

**Comment by nicolevasilevsky** [comment]
I am not familiar with the dateTime annotation - would that allow you to add a string, or would you pick from a dropdown? I imagine some of the date would be in minutes or hours, but maybe some of it would be in quarters or semesters too.

**Comment by marijane** [comment]
Here's a nice overview of xsd:dateTime.
http://books.xmlschemata.org/relaxng/ch19-77049.html
and now that I read it, i realize it's inappropriate, because it requires all parts, including the date.

there is an xsd:duration, but it's not one of Protege's built-in datatypes, interesting.
http://books.xmlschemata.org/relaxng/ch19-77073.html

I don't know what eagle-i might do with the date/time datatypes.  this is one of those times i wish i had my own instance to experiment with.
