### ISSUE TITLE
expand the organization subhiearchy?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#49]
copyright holders can be organizations, but the types of organizations that may hold copyrights may be more extensive than the 3 subtypes currently in the ontology. Should this subhierarchy be expanded?

**Comment by nicolevasilevsky** [comment]
It looks like you can omit adding a more specific org type and it will default to organization, but this i not super obvious from a data entry standpoint.

**Comment by marijane** [comment]
The subtypes I've included in the ontology are all ones that I know for sure will be providing resources for NLighten 1.0. I don't have the best sense of what other types of organizations might provide clinical research educational resources.

Here is a screenshot of all the organization subtypes from the VIVO ontology:
![screen shot 2017-12-14 at 5 08 49 pm](https://user-images.githubusercontent.com/1771847/34022066-f901a3b4-e0f1-11e7-9026-0dac72fed2b0.png)

**Comment by nicolevasilevsky** [comment]
Maybe ultimately you may want to consider bringing in that whole branch from VIVO-ISF, but maybe not necessary for the 1.0 release.

**Comment by marijane** [comment]
Yeah, I set up some milestones to separate issues for a future release from the initial release.
