### ISSUE TITLE
has depth has no choices

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#50]
there are not any terms in the has depth field.

Also, I'm not sure what has depth means?

**Comment by nicolevasilevsky** [comment]
same with has format

**Comment by marijane** [comment]
This is a bug I've been meaning to file.  The drop-down box gets drawn in the wrong place.  Scroll up after clicking and I bet you will find it.

**Comment by skcheng** [comment]
This is a known bug with the application. It wasn't prioritized because it was hard to reproduce and didn't happen that often. I'm not sure why it's being so rampant now. For expediency & sanity sake, I'm disinclined to address known bugs, unless otherwise directed.

**Comment by nicolevasilevsky** [comment]
Oh yeah, you are right @marijane.
@skcheng- fine with me if you want to make known bugs a lower priority. :)

**Comment by marijane** [comment]
I've tagged this as wontfix and I'm going to close it.  That said, my gut says it might need to be, because the behavior is pretty consistent on the NLighten instance.
