### ISSUE TITLE
should audience type have so many fields?

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#51]
what kind of identifier and URL would you expect for an audience type?

**Comment by nicolevasilevsky** [comment]
same with duration

![image](https://user-images.githubusercontent.com/6722114/33969684-81172654-e023-11e7-9030-35595e32b0df.png)

**Comment by marijane** [comment]
This is because the domain of those properties is owl:Thing.  This looks like another argument in favor of refactoring the model for these entities.

#47

**Comment by nicolevasilevsky** [comment]
👍

**Comment by marijane** [comment]
Identifier refactor will be addressed in #57.

I am going to add some domain restrictions on url so it only shows up on primary resources.
