### ISSUE TITLE
resources for organization are not appearing on left side bar

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#52]
I created several resources under the org "OHSU". When I click on the left side bar for all resource types, none of the resources are displayed.

![image](https://user-images.githubusercontent.com/6722114/33969726-b718cf78-e023-11e7-8129-d0f74e85e41b.png)

**Comment by skcheng** [comment]
My guess is that there is no inverse property defined for provider. I think we need a provided_by property/field/thing and it should be annotated as inverse like #41

**Comment by marijane** [comment]
I added a property called "provides" and made it the inverse of provider.  It has the same annotations as provider, meaning it's in the PrimaryProperty group and the ResourceProvider group.

**Comment by marijane** [comment]
@nicolevasilevsky can you confirm whether this has been fixed?

**Comment by nicolevasilevsky** [comment]
not fixed. it is still not working as expected, unfortunately

**Comment by skcheng** [comment]
@nicolevasilevsky Do you mind testing this again? It looks like I may have uploaded the updated app with Marijane's changes after you last checked. Sorry about that. I just looked in SWEET at all resources for Harvard Catalyst and it is listing them as expected.

**Comment by nicolevasilevsky** [comment]
Yes! Seems to be working now!

![image](https://user-images.githubusercontent.com/6722114/36764447-843361d2-1be1-11e8-8e6d-f209fd23f404.png)

**Comment by marijane** [comment]
Can we close this?

**Comment by nicolevasilevsky** [comment]
yes!
