### ISSUE TITLE
issue with duration pulling in option from other orgs

### ISSUE THREAD

**Issue by nicolevasilevsky** [NLightenGroup/nlighten-ontology#54]
when I go to create a new educational resource, for has duration, it gives me the option to chose from all organizations:
![image](https://user-images.githubusercontent.com/6722114/33970042-b36431e0-e025-11e7-9f24-16ceb5ced2aa.png)

However, if I click Chose from dropdown, create new, but then want to go back and choose an existing record, I click the circle arrow button. But then the option to 'chose from all organizations' has gone away:

![image](https://user-images.githubusercontent.com/6722114/33970084-e2b3ec6a-e025-11e7-8c09-8e4131f5c794.png)

So if I make this mistake, I can no longer link to an existing record.

**Comment by marijane** [comment]
Another argument for changing the Duration model, I think.  #47.

**Comment by skcheng** [comment]
I'm not sure if I'm reproducing this correctly:

`has duration`:
1. Click on drop down and choose `<create new>`
2. Verified the option for seeing choices from all organizations goes away
3. Click on drop down again and choose `Choose from dropdown`
4. I can see the `See choices from all organizations`

@nicolevasilevsky am I reproducing this correctly?

**Comment by nicolevasilevsky** [comment]
Interesting! Your workflow seems to work. But if I do:

1. Click on drop down and choose <create new>
2. Verified the option for seeing choices from all organizations goes away
3. Click the arrow button
![image](https://user-images.githubusercontent.com/6722114/34007842-0faa3cc8-e0b8-11e7-8360-a0753b2bb0ab.png)

then the See choices from all organizations does not come back
