### ISSUE TITLE
Set up has part/part of for educational resources

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#59]
OSU is importing resources such that each part of a Common Cartridge will have its own eagle-i identifier.  has part/part of have been pulled into NLN, but they are currently excluded.  We should remove the exclusion and add constraints that allow parts of resources to be related to each other.

**Comment by nicolevasilevsky** [comment]
I remember this feature was highly desired in eagle-i, but I don't think it was something we were ever able to implement. But maybe @skcheng can comment further.

**Comment by marijane** [comment]
Well, I am going to take a stab at it! =D

**Comment by nicolevasilevsky** [comment]
👍
