### ISSUE TITLE
How do we feel about the property groupings?

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#61]
Do they make sense?  Should any of them move?  We have three groupings to work with.

**Comment by nicolevasilevsky** [comment]
maybe group email and phone # together on organization and person

**Comment by nicolevasilevsky** [comment]
maybe put first name, last name above additional name on person, and title before description

**Comment by marijane** [comment]
I have no control over additional name, that's built into the software.

**Comment by nicolevasilevsky** [comment]
in eagle-i, we always had Web address at the bottom, so maybe move that to the bottom on the educational resources page
