### ISSUE TITLE
Search facets don't seem to be surfacing in the UI

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#68]
**Steps to repro:**
1. navigate to https://alaska.dev.eagle-i.net/institution/
2. Observe the filters

**Result**:
You can only filter resources by resource type

**Expected Result:**
I annotated the domain(competency), depth (training level), and audience relationships as members of the SearchFacet Property Group.  I expect to be able to filter by these properties, but they are not showing up in the UI.

**Comment by skcheng** [comment]
See issue 76
