### ISSUE TITLE
Change "has_synonym" annotations to use "alternative term" instead

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#77]
Examples: IRB, GCP
eagle-i seems to favor rdfs:label?

**Comment by nicolevasilevsky** [comment]
Hey @marijane - from what I remember, you should see the synonyms in the dropdown lists with ontology terms. What is the context where you are seeing (or not seeing) IRB or GCP? If the ontology term is used for a label of a field, then the label will be used, not the synonym. But if there is a dropdown list, you should see the primary label and the synonym in the list. But I think they are usually in alphabetical order, there isn't a way to easily see that a term is a synonym. Does this clarify/make sense?

**Comment by marijane** [comment]
@nicolevasilevsky:

In the ontology search box at https://alaska.dev.eagle-i.net/model/.

If I type in "IRB", it doesn't find anything, despite the fact that the "Institutional Review Board" class is annotated with has_synonym "IRB".  Similar situation with "GCP"/"Good Clinical Practice" and "HIPAA"/"Health Insurance Portability and Accountability Act".  

Conversely, if I type in "Drugs", I get both "Investigational Drugs" and "Drugs, Investigational" in the typeahead/drop-down hint box.  In this case, "Drugs, Investigational" is the rdfs:label and "Investigational Drugs" is the preferredLabel.  I didn't actually expect the rdfs:label to show up here, but it does, and it also shows up at the page for the term at https://alaska.dev.eagle-i.net/model/#q=Investigational%20Drugs&t=http://purl.bioontology.org/ontology/MESH/D015507&of=score

You can also see this with "Biologics" and "Training Level" -- the rdfs:labels show up as synonyms.

As such, I concluded the software is treating rdfs:labels as synonyms when a preferredLabel is present.  It seems to be ignoring the has_synonym annotations entirely.

**Comment by skcheng** [comment]
@marijane Yes, eagle-i does not 'understand' the has_synonym annotation. It's using a different mechanism for this. I think I found some Protege instructions on how to do this in a way eagle-i understands:
https://docs.google.com/document/d/1Radat4PqKJuWktxJ3RgxWp_osfW07RZ6-EBVLG8YAsw/edit#heading=h.hho6q4jyvwi1

**Comment by marijane** [comment]
Thank you @skcheng!  I see 'alternative term' as an available annotation property in Protege.  This should be an easy fix.

**Comment by nicolevasilevsky** [comment]
Oh yes, alternative term, I remember that now... :)

**Comment by nicolevasilevsky** [comment]
Good catch @skcheng!

**Comment by skcheng** [comment]
Aw, shucks, thanks 😸 

... also ... I should probably extract that helpful bit of information out of the document and onto the wiki 😀
