### ISSUE TITLE
Are Device and Medical Therapeutic Devices redundant?

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#85]
Not sure why I didn't notice this earlier, but these seem to be synonyms, and if so, I should deprecate one of them.

**Comment by marijane** [comment]
Also should consider making the preferred label on Device plural, and whether the other Device categories should become subclasses of it.

**Comment by pitviper6** [comment]
Do we expect to have any other kind of devices added? I dunno...like...maybe diagnostic devices? Are those considered therapeutic?

**Comment by marijane** [comment]
I'm not sure.  And I should note that Device is just a preferred label for Medical Device -- Device seems to be the term preferred by our subject matter experts.

**Comment by pitviper6** [comment]
Maybe make the preferred label plural and allow subclasses in case?
I'm probably breaking some big ontology rule by saying "in case" lol.

**Comment by marijane** [comment]
Ha!
Since the clinical research competencies are a referenced taxonomy, I'm looking at these classes with more of a taxonomist/thesaurus construction eye.  Which is where the inclination to make labels plural comes from!  Ontologies tend to use singular forms.

**Comment by marijane** [comment]
I'm going to deprecate Medical Therapeutic Device because I added it later, and I am going to go ahead and make Device plural since I made Drug plural too.
