### ISSUE TITLE
Should Investigational Drugs be a subclass of Drug?

### ISSUE THREAD

**Issue by marijane** [NLightenGroup/nlighten-ontology#86]
And should the preferred label on Drug be plural?

**Comment by nicolevasilevsky** [comment]
I think it should be single, not plural.

**Comment by marijane** [comment]
As noted in #85, since this is part of the taxonomy, I am inclined to follow taxonomy conventions.  ANSI/NISO z39.19 section 6.5 suggests that count nouns should normally be expressed as plurals. 

I also think that using plurals lends itself better to making the taxonomy more hierarchical along a broader/narrower term structure rather than a super/subclass structure.  I need to think about whether that's something we'd want here, since the ontology browser UI only shows one level of a hierarchy at a time.

**Comment by marijane** [comment]
Actually I just realized, even though it's a taxonomy, the software still treats it in an ontological sense, such that subclasses inherit all their parent classes in the browser.  I think that's an argument for less hierarchy overall, but I think it helps me answer the question I posed in this ticket -- an investigational drug is a type of drug, so yes, it should be a subclass of drug.

**Comment by marijane** [comment]
And I'm going to pluralize the preferred label because the rdfs:label is plural and it's soon-to-be subclass is also plural.
