### ISSUE TITLE
“View Resource Stubs” functionality is not populating

### ISSUE THREAD

**Issue by pitviper6** [NLightenGroup/nlighten-ontology#9]
I have created a draft record for the organization the FDA, but it is not appearing under the "My Resource Stubs" link.

http://alaska.dev.eagle-i.net/i/00000160-37a9-d7a2-3e79-9e4880000000

**Comment by nicolevasilevsky** [comment]
+1

**Comment by skcheng** [comment]
This is expected. An organization isn't considered a resource. You should be able to see it in the pull down from the workbench... which you can't at the moment. I need to tinker with the installation.

**Comment by skcheng** [comment]
This is now all set, organizations are showing up in the drop down.
